"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/header/header";
import { RecoilRoot } from "recoil";
import Footer from "./component/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <RecoilRoot>
      <html lang="en">
        <body>
          <main>
            <Header />
            {children}
            <Footer />
          </main>
        </body>
      </html>
    </RecoilRoot>
  );
}
